### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by illegitimate-egg** [AngelJumbo/suckless#1]
Do I recompile DWM with these files replaced? Do I compile it from this source? What do I do?

**Comment by AngelJumbo** [comment]
If you already are using dwm all you need to do is `sudo make install ` in my dwm folder, you have to do the same with dwmblocks well if you want my c modules you have to compile them and add them to your path to.
If it's the first time that you are using dwm just search how to install dwm there's a lot of tutorials.
